<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.22000.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SoftHolding.QUEDICHO.Application/SoftHolding.QUEDICHO.Application.csproj" />
    <ProjectReference Include="../SoftHolding.QUEDICHO.Audio/SoftHolding.QUEDICHO.Audio.csproj" />
    <ProjectReference Include="../SoftHolding.QUEDICHO.Domain/SoftHolding.QUEDICHO.Domain.csproj" />
    <ProjectReference Include="../SoftHolding.QUEDICHO.Infrastructure/SoftHolding.QUEDICHO.Infrastructure.csproj" />
    <ProjectReference Include="../SoftHolding.QUEDICHO.Transcription/SoftHolding.QUEDICHO.Transcription.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.Async" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
